using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Alerts.Logic.Enums
{
    public enum Coins
    {
        INIT, ABT, ACT, ADA, ADX, AE, AGI, AGRS, AION, AMB, AMP, ANT, APPC, ARDR, ARK, ARN, ARY, AST, ATM, AUTO, BAT,
        BAY, BCC, BCD, BCH, BCN, BCO, BCPT, BDL, BELA, BIX, BLCN, BLK, BLOCK, BLZ, BNB, BNT, BNTY, BOS, BPT, BQ, BRD,
        BTC, BTCD, BTCP, BTCZ, BTG, BTM, BTS, BTX, BURST, CDN, CDT, CHIPS, CIX, CLAM, CLOAK, CMT, CND, CNX, CNY, COB,
        CRED, CRPT, CS, CTR, CVC, DASH, DAT, DATA, DBC, DCN, DCR, DENT, DEW, DGB, DGD, DLT, DNT, DOGE, DRGN, DTA,
        DTR, EBST, EDG, EDO, EDOGE, ELF, ELIX, ELLA, EMC, EMC2, ENG, ENJ, EOS, EQUA, ETC, ETH, ETHOS, ETN, ETP, EUR,
        EVX, EXMO, EXP, FAIR, FCT, FIL, FLDC, FLO, FSN, FTC, FUEL, FUN, GAME, GAS, GBP, GBX, GBYTE, GENERIC, GNO,
        GNT, GRC, GRS, GTO, GUP, GVT, GXS, HPB, HSR, HTML, HUC, HUSH, ICN, ICX, IGNIS, INK, INS, ION, IOP, IOST,
        IOTA, ITC, JNT, JPY, KCS, KIN, KMD, KNC, KRB, LBC, LEND, LINK, LKK, LRC, LSK, LTC, LUN, MAID, MANA, MCAP,
        MCO, MDA, MDS, MED, MIOTA, MKR, MLN, MNX, MOD, MONA, MTH, MTL, MUSIC, MZC, NANO, NAS, NAV, NCASH, NDZ, NEBL,
        NEO, NEOS, NGC, NLC2, NLG, NMC, NULS, NXS, NXT, OAX, OMG, OMNI, ONT, OST, OX, PART, PASL, PAY, PINK, PIRL,
        PIVX, PLR, POA, POE, POLY, POT, POWR, PPC, PPP, PPT, PRL, PURA, QASH, QIWI, QLC, QRL, QSP, QTUM, R, RADS,
        RCN, RDD, RDN, REP, REQ, RHOC, RIC, RISE, RLC, RPX, RUB, RVN, SALT, SAN, SBD, SBERBANK, SC, SKY, SLR, SLS,
        SMART, SNGLS, SNM, SNT, SPANK, SPHTX, SRN, START, STEEM, STORJ, STORM, STRAT, SUB, SYS, TAAS, TAU, TEL,
        THETA, TIX, TKN, TNB, TNC, TNT, TRIG, TRX, TZC, UBQ, UNITY, USD, USDT, UTK, VEN, VERI, VIA, VIB, VIBE, VIVO,
        VRC, VTC, WABI, WAVES, WAX, WGR, WINGS, WPR, WTC, XAS, XBC, XBY, XCP, XDN, XEM, XLM, XMG, XMR, XMY, XP, XPA,
        XPM, XRB, XRP, XTZ, XUC, XVC, XVG, XZC, YOYOW, ZCL, ZEC, ZEN, ZIL, ZRX
    }
}
